### ISSUE TITLE
There is an error in the readme file, No detailed instructions yet

### ISSUE THREAD

**Issue by khaicm-0897** [sun-asterisk/tech-standard-php-auth#12]
# wrong function logout in readme file
# There is no link to the wiki guide yet

**Comment by dungda-0794** [comment]
@khaicm-0897 khai
So sorry. It is my mistake. Thanks you for your report.

**Comment by dungda-0794** [comment]
Thanks for your pull https://github.com/sun-asterisk/tech-standard-php-auth/pull/13
